import type { BreakdownId, GroupId, IndicatorId } from '@/data/types'

/**
 * Vocabulary for the rule-based analyst. Plain data — extend it without touching the parser.
 * Phrases are matched on normalised text (lower case, accents removed, "&" → "and"), longest
 * first, on word boundaries.
 */

/** Indicator phrases, most specific first. */
export const INDICATOR_PHRASES: [string, IndicatorId][] = [
  ['gender gap', 'genderGapAccount'],
  ['income gap', 'incomeGapAccount'],
  ['without an account', 'noAccount'],
  ['without account', 'noAccount'],
  ['no account', 'noAccount'],
  ['unbanked', 'noAccount'],
  ['financial institution account', 'fiAccount'],
  ['bank account', 'fiAccount'],
  ['mobile money only', 'mobileMoneyAccount'],
  ['mobile money', 'mobileMoneyAccount'],
  ['mobile wallet', 'mobileMoneyAccount'],
  ['digital payments', 'digitalPayments'],
  ['digital payment', 'digitalPayments'],
  ['paid digitally', 'madeDigitalPayment'],
  ['merchant payment', 'digitalMerchantPayment'],
  ['pay bills online', 'onlineBillPayment'],
  ['online shopping', 'onlinePurchase'],
  ['bought online', 'onlinePurchase'],
  ['debit card', 'debitCard'],
  ['credit card', 'creditCard'],
  ['wages', 'wagesIntoAccount'],
  ['salary', 'wagesIntoAccount'],
  ['government transfer', 'govTransferIntoAccount'],
  ['government payment', 'govTransferIntoAccount'],
  ['formal savings', 'formalSavings'],
  ['saved formally', 'formalSavings'],
  ['savings club', 'savedInformal'],
  ['informal savings', 'savedInformal'],
  ['informal saving', 'savedInformal'],
  ['old age', 'savedOldAge'],
  ['savings', 'savedAny'],
  ['saving', 'savedAny'],
  ['saved', 'savedAny'],
  ['formal borrowing', 'formalBorrowing'],
  ['formal credit', 'formalBorrowing'],
  ['borrowed formally', 'formalBorrowing'],
  ['borrow from family', 'borrowedFamily'],
  ['family or friends', 'borrowedFamily'],
  ['borrowed for business', 'borrowedForBusiness'],
  ['business loan', 'borrowedForBusiness'],
  ['borrowing', 'borrowedAny'],
  ['borrowed', 'borrowedAny'],
  ['borrow', 'borrowedAny'],
  ['credit', 'formalBorrowing'],
  ['loan', 'formalBorrowing'],
  ['loans', 'formalBorrowing'],
  ['emergency funds', 'emergencyFundsPossible'],
  ['emergency', 'emergencyFundsPossible'],
  ['resilience', 'emergencyFundsPossible'],
  ['inactive account', 'inactiveAccount'],
  ['dormant', 'inactiveAccount'],
  ['mobile phone', 'mobilePhone'],
  ['phone', 'mobilePhone'],
  ['internet', 'internetUse'],
  ['online', 'internetUse'],
  ['account ownership', 'accountOwnership'],
  ['financial inclusion', 'accountOwnership'],
  ['accounts', 'accountOwnership'],
  ['account', 'accountOwnership'],
  ['banked', 'accountOwnership'],
]

/** Population-group phrases. */
export const GROUP_PHRASES: [string, GroupId][] = [
  ['women', 'women'],
  ['woman', 'women'],
  ['female', 'women'],
  ['men', 'men'],
  ['male', 'men'],
  ['poorest', 'poorest40'],
  ['poor', 'poorest40'],
  ['low income households', 'poorest40'],
  ['richest', 'richest60'],
  ['rich', 'richest60'],
  ['wealthier', 'richest60'],
  ['rural', 'rural'],
  ['urban', 'urban'],
  ['young', 'age15to24'],
  ['youth', 'age15to24'],
  ['older', 'age25plus'],
  ['primary education', 'primaryOrLess'],
  ['secondary education', 'secondaryOrMore'],
  ['unemployed', 'outOfLaborForce'],
  ['out of the labor force', 'outOfLaborForce'],
  ['in the labor force', 'inLaborForce'],
]

/** Phrases that name a breakdown (for gap questions). */
export const BREAKDOWN_PHRASES: [string, BreakdownId][] = [
  ['gender', 'sex'],
  ['women and men', 'sex'],
  ['men and women', 'sex'],
  ['income', 'income'],
  ['rich and poor', 'income'],
  ['poor and rich', 'income'],
  ['education', 'education'],
  ['age', 'age'],
  ['youth', 'age'],
  ['labor force', 'labor'],
  ['employment', 'labor'],
  ['rural and urban', 'urbanicity'],
  ['urban and rural', 'urbanicity'],
  ['rural', 'urbanicity'],
  ['location', 'urbanicity'],
]

/** Extra names for aggregates and economies (normalised text → entity code). */
export const ENTITY_ALIASES: [string, string][] = [
  ['the world', 'WLD'],
  ['world', 'WLD'],
  ['global', 'WLD'],
  ['globally', 'WLD'],
  ['worldwide', 'WLD'],
  ['developing economies', 'LMY'],
  ['developing countries', 'LMY'],
  ['developing world', 'LMY'],
  ['sub saharan africa', 'SSA'],
  ['subsaharan africa', 'SSA'],
  ['africa', 'SSA'],
  ['south asia', 'SAS'],
  ['east asia', 'EAP'],
  ['latin america', 'LAC'],
  ['middle east', 'MNA'],
  ['north africa', 'MNA'],
  ['europe and central asia', 'ECA'],
  ['central asia', 'ECA'],
  ['high income economies', 'HIC'],
  ['high income countries', 'HIC'],
  ['rich countries', 'HIC'],
  ['low income economies', 'LIC'],
  ['low income countries', 'LIC'],
  ['lower middle income', 'LMC'],
  ['upper middle income', 'UMC'],
  ['usa', 'USA'],
  ['united states', 'USA'],
  ['america', 'USA'],
  ['uk', 'GBR'],
  ['britain', 'GBR'],
  ['uae', 'ARE'],
  ['drc', 'COD'],
  ['south korea', 'KOR'],
  ['korea', 'KOR'],
  ['russia', 'RUS'],
  ['ivory coast', 'CIV'],
  ['turkey', 'TUR'],
]

/** Words that should never be read as an entity even if a name contains them. */
export const STOPWORDS = new Set(['and', 'or', 'the', 'in', 'of', 'for', 'to', 'vs', 'with'])
